### PR TITLE
jedi 0.19.1

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Destination channel:** main

### Links

- [PKG-5266](https://anaconda.atlassian.net/browse/PKG-5266) 
- [Upstream repository](https://github.com/davidhalter/jedi/tree/v0.19.1)
- Changelog: https://github.com/davidhalter/jedi/blob/v0.19.1/CHANGELOG.rst
- Requirements: https://github.com/davidhalter/jedi/blob/v0.19.1/setup.py

### Explanation of changes:

- Clean up the recipe
- Update runtime pinning

[PKG-5266]: https://anaconda.atlassian.net/browse/PKG-5266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ifitchet** [comment]
There's a `python_requires='>=3.6'` in `setup.py`.  Should we add that for completeness?

Also, check the branch protection rules and delete on merge flag.

**Comment by skupr-anaconda** [comment]
> There's a `python_requires='>=3.6'` in `setup.py`. Should we add that for completeness?
> 
> Also, check the branch protection rules and delete on merge flag.

It's already there https://github.com/AnacondaRecipes/jedi-feedstock/pull/7/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR16

**Comment by ifitchet** [comment]
No tests?

**Comment by skupr-anaconda** [comment]
> * https://github.com/davidhalter/jedi/blob/v0.19.1/setup.py

The upstream tests are broken:
```
test/completion/__init__.py:6: in <module>
    from . import imports
E     File "$SRC_DIR/test/completion/imports.py", line 53
E       a = import_tree.pkg.mod1.
E                                ^
E   SyntaxError: invalid syntax
```

**Comment by ifitchet** [comment]
> The upstream tests are broken:

Should we have a quick comment in the recipe so that people are aware -- and don't repeat my question?

**Review by danpetry — APPROVED** [review]

**Review by cbouss — APPROVED** [review]
LGTM. (I don't see much point in running tests here. It's a python package, with only one dependency and a rather strict pinning to it.)

**Pull request merged**
